jobs:
  kafka:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          build-args: |-
            kafka_version=${{ inputs.kafka }}
            scala_version=${{ inputs.scala }}
            zookeeper_version=${{ inputs.zookeeper }}
          context: .
          file: https://github.com/muicoder/koperator/raw/refs/heads/master/docker/Dockerfile.kafka
          platforms: linux/amd64,linux/arm64
          provenance: false
          pull: true
          push: true
          sbom: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kafka:${{ inputs.scala }}-${{ inputs.kafka }}
  zookeeper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          build-args: |-
            zookeeper_version=${{ inputs.zookeeper }}
          context: .
          file: https://github.com/muicoder/koperator/raw/refs/heads/master/docker/Dockerfile.zookeeper
          platforms: linux/amd64,linux/arm64
          provenance: false
          pull: true
          push: true
          sbom: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/zookeeper:${{ inputs.zookeeper }}
name: buildImage::kafka
on:
  workflow_dispatch:
    inputs:
      kafka:
        default: "2.8.2"
        description: Meta
        required: true
        type: string
      scala:
        default: "2.12"
        description: Meta
        required: true
        type: string
      zookeeper:
        default: "3.8.5"
        description: Meta
        required: true
        type: string
